### Note: DO NOT use quantized model or quantization_bit when merging lora adapters

### model
model_name_or_path: /root/autodl-tmp/models/Meta-Llama-3.1-8B/
adapter_name_or_path: /root/code/LLaMA-Factory/saves/Meta-Llama-3.1-8B/lora/train_2024-11-25-20-27-47
template: llama3
finetuning_type: lora

### export
export_dir: /root/autodl-tmp/models/Meta-Llama-3.1-8B-merged
export_size: 4
export_device: cuda
export_legacy_format:   
